### ISSUE TITLE
bash: HOST: No such file or directory error on docker

### ISSUE THREAD

**Issue by d3lac** [R0GGER/public-iperf3-servers#1]
When I run docker command,

`docker run -it --rm -p 5201:5201 -p 5201:5201/udp r0gger/iperf3-speedtest -c <HOST> -p $((5200+(RANDOM%10)))`

I see the below error,

`bash: HOST: No such file or directory`

Something to do with `<HOST>` tag. Please check

**Comment by R0GGER** [comment]
Host is an address from the column "Command".

docker run -it --rm -p 5201:5201 -p 5201:5201/udp r0gger/iperf3-speedtest -c ams.speedtest.clouvider.net -p $((5200+(RANDOM%10)))
