### ISSUE TITLE
IP-Projects Server Changed

### ISSUE THREAD

**Issue by jnthn-b** [R0GGER/public-iperf3-servers#12]
For IP-Projects, the Server Listed here on GitHub is lg.ip-projects.de, but we have moved over to speedtest.ip-projects.de. 
The Site already represents that, but on GitHub it still shows the old lg Server :)

**Comment by R0GGER** [comment]
Perfect! I will change it a.s.a.p.
And is ipv6 supported and how about speed (GB/s)?

**Comment by R0GGER** [comment]
https://github.com/R0GGER/public-iperf3-servers/commit/e213a50ec70d424cff42da4049f9e3a1f5c69623

**Comment by jnthn-b** [comment]
Perfect 👍 
The Server is also running IPv6 and has a 10Gbit Link :)
