### ISSUE TITLE
Poda.cz (Czech ISP, providing service in between Brno and Ostrava)

### ISSUE THREAD

**Issue by webknjaz** [R0GGER/public-iperf3-servers#13]
```console
$ iperf3 -c rychlost.poda.cz -V -R -P 10 -t 60
...
[SUM]   0.00-60.00  sec  1.36 GBytes   194 Mbits/sec  14445             sender
[SUM]   0.00-60.00  sec  1.35 GBytes   193 Mbits/sec                  receiver
snd_tcp_congestion cubic
rcv_tcp_congestion cubic

iperf Done.
```

My ISP-provided download limit is around 200 Mbit/s (Netserv.cz in the city of Mikulov) so I don't know what's this server's uplink (they don't even advertise at http://rychlost.poda.cz that it supports iperf) but I know that Poda.cz itself provides fiber to subscribers with up to 2 Gbps plans where they have coverage (https://www.poda.cz/2gbps/).

**Comment by R0GGER** [comment]
Nice find! I will test and monitor this one a bit before adding it to the list.

**Comment by webknjaz** [comment]
FWIW I've been using Poda.cz as my ISP for about 2-3 years, before I moved to another town that doesn't have their coverage. And I remember running iperf3 against this server occasionally. Haven't noticed any downtime on their side.

**Comment by R0GGER** [comment]
Server added to the list. Thanks!

**Comment by webknjaz** [comment]
@R0GGER the server location is Ostrava. Mikulov is my location, not theirs.

**Comment by R0GGER** [comment]
Oops... fixed. Thanks again!
