### ISSUE TITLE
NL iperf ipv4 / ipv6

### ISSUE THREAD

**Issue by MarcHagen** [R0GGER/public-iperf3-servers#17]
https://novoserve.com/speedtest
IPv4 + IPv6
speedtest.novoserve.com
Ports available for testing are 5201 to 5206

Currently 40Gbit connection, but will be increased to 100Gbit

**Comment by R0GGER** [comment]
Thanks for your addition.
I removed your iperf3 server a few months ago because it had a poor 30-day uptime.

I'll update the list asap.

**Comment by MarcHagen** [comment]
Oh I was not aware of any uptime issues. 
the server is quite busy on the 9 ports we have but shouldn’t impact ping/up checks.

**Comment by R0GGER** [comment]
I doing TCP checks...

**Comment by R0GGER** [comment]
Done, list updated.

**Comment by MarcHagen** [comment]
Thanks! Now I know that I need to keep a (little) close eye on it.

**Comment by R0GGER** [comment]
[monitoring badge](https://uptime.iperf3serverlist.net/api/badge/287/uptime/24?style=flat-square) @ port 5201.

**Comment by MarcHagen** [comment]
Hi just curious, I saw you added a label `UNTESTABLE: 5201-5206`
Could you please explain what this means?

Also, we just got a bad week of outages on the pop this server is located on. 😢

**Comment by R0GGER** [comment]
Yeah... I can't test port 5201-5206 because as soon as I do, your server goes down. However the server seems up, because I can do a manual test via iperf3 -c <server-name>.
It seems my connection (vps) gets blocked on a specific port after multiple tcp pings (every 5 minutes).

**Comment by MarcHagen** [comment]
Ah oke, we can ping/check the port(s) just fine indeed even with UptimeKuma.
Of course, there is protection and filtering but not for that amount of traffic.
