### ISSUE TITLE
Additional iperfs

### ISSUE THREAD

**Issue by thornpeak** [R0GGER/public-iperf3-servers#2]
Origin: https://iperf.fr/iperf-servers.php#public-servers

nl.iperf.014.fr port 10420 -R, 1gbit, NL, tested
iperf.astra.in.ua port 5201 to 5206, -R, 10gbit, UA, tested
iperf.volia.net, port 5201, -R, unknown, UA, tested

**Comment by R0GGER** [comment]
Thanks! I found some other ones myself too... I will test and add them as soon as possible.

**Japan**
iperf3 -4 -c 156.59.29.2 -p 5201 -P 4 (-R)
Speed: ??

**Hong Kong**
iperf3 -4 -c 156.59.103.69 -p 5201 -P 4 (-R)
Speed: ??

**Singapore**
iperf3 -4 -c 23.90.191.146 -p 5201 -P 4 (-R)
Speed: ??

**Bangkok, Thailand**
iperf3 -4 -c 129.227.231.194 -p 5201 -P 4 (-R)
Speed: ??

**Jakarta, Indonasia**
iperf3 -4 -c 129.227.44.98 -p 5201 -P 4 (-R)
Speed: ??

**Manila, Philippines**
iperf3 -4 -c 156.59.169.4 -p 5201 -P 4 (-R)
Speed: ??

**Sao Paulo, Brazil**
iperf3 -4 -c 128.1.240.146 -p 5201 -P 4 (-R)
Speed: ??

**Hanoi, Vietnam**
iperf3 -4 -c 156.59.143.226 -p 5201 -P 4 (-R)
Speed: ??

**Comment by R0GGER** [comment]
Thanks list updated.
