### ISSUE TITLE
Add iperf3 servers

### ISSUE THREAD

**Issue by cyfran** [R0GGER/public-iperf3-servers#24]
Hello, 
 
We are running iPERF3 servers in our infrastructure. 

Our website: https://mirhosting.com

Can you add it to your  public iperf3 servers list? 
 
iperf3 -c speedtest.nl1.mirhosting.net -p 5201-5209 (recursive and ipv6 acceptable), connectivity 2x10Gbps, location: NL Dronten, DC Serverius
iperf3 -c speedtest.nl3.mirhosting.net -p 5201-5209 (recursive and ipv6 acceptable), connectivity 40Gbps, location: NL Amsterdam, DC Nikhef

Contact information: https://mirhosting.com or https://mirhosting.com/contact

If you require any additional information, we will be happy to provide it.

Thank you!

**Comment by R0GGER** [comment]
Great! I will add your servers asap.

**Comment by R0GGER** [comment]
root@dev:~# test speedtest.nl1.mirhosting.net
185.15.210.116 -> [5060,8080]
Port: 5201-5209 closed

root@dev:~# iperf3 -c speedtest.nl1.mirhosting.net
iperf3: error - unable to send control message: Bad file descriptor

root@dev:~# test speedtest.nl3.mirhosting.net
185.15.209.167 -> [80,5060,8080]
Port: 5201-5209 closed

root@dev:~# iperf3 -c speedtest.nl3.mirhosting.net
iperf3: error - unable to send control message: Bad file descriptor

**Comment by cyfran** [comment]
Sorry for my mistake, the ports are open now. Thank you!

**Comment by R0GGER** [comment]
Great!

**Comment by R0GGER** [comment]
Done! Commit: https://github.com/R0GGER/public-iperf3-servers/commit/0376f2bc008e125c315fa001f3d2a2f717c614d7
