### ISSUE TITLE
bad location

### ISSUE THREAD

**Issue by marczz** [R0GGER/public-iperf3-servers#25]
iperf.online.net from Scaleway is erroneously said to be in Vienna, it should be in or near Paris.

**Comment by R0GGER** [comment]
Thanks! Correction: https://github.com/R0GGER/public-iperf3-servers/commit/1d7bd4b103db9bff54b8ca6e5e757776c58b3afc

**Comment by JBSC** [comment]
this issue came back on  https://github.com/R0GGER/public-iperf3-servers/commit/b0e941569a3f2f478db5734381039175b5e2aa06#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R151

**Comment by R0GGER** [comment]
My bad...
The location was wrong in the database (nocodb), from Nocobd I export all the fields with a custom converter (php).
