### ISSUE TITLE
CDN77 servers incomplete

### ISSUE THREAD

**Issue by totoCZ** [R0GGER/public-iperf3-servers#26]
You can add a few more from as60068

https://www.datapacket.com/looking-glass

All run iperf3.

**Comment by totoCZ** [comment]
There's a secret DNS for them but you can simply steal the JSON from the webpage if you want to

https://www.datapacket.com/_next/data/cBM5UDxKJJ1Mw-XkF0LWG/looking-glass/amsterdam.json?location=amsterdam

**Comment by R0GGER** [comment]
Yup... I know! Thanks.
Not all are listed at github.

List: https://db.iperf3serverlist.net/dashboard/#/nc/view/eb7cdc41-538d-45fb-8c94-5576e759cbc1

@totoCZ 

> There's a secret DNS...

Interesting, do you have more info?

**Comment by totoCZ** [comment]
It's an internal domain https://pastebin.com/wBAaEH85 you can use it for your own testing but it's better not to advertise it publicly for casual attackers who don't know it.

**Comment by R0GGER** [comment]
> It's an internal domain https://pastebin.com/wBAaEH85 you can use it for your own testing but it's better not to advertise it publicly for casual attackers who don't know it.

Aha... :+1: I'll use public IP's only.

**Comment by R0GGER** [comment]
Great, I'll edit this @github and iperf3serverlist.net asap.

**Comment by R0GGER** [comment]
Fixed, https://github.com/R0GGER/public-iperf3-servers/commit/b0e941569a3f2f478db5734381039175b5e2aa06

**Comment by strunzoz** [comment]
I was hoping to be corrected without needing to ask the question: how do I find more cdn77 iperf3 servers

**Comment by R0GGER** [comment]
Yes, of course there are more... But then you need advanced tools and access to these tools (license) to find these servers.
Tools you can try are: Censys and Shodan.
