### ISSUE TITLE
YABS Collab

### ISSUE THREAD

**Issue by masonr** [R0GGER/public-iperf3-servers#8]
Your project caught my eye as I was looking to do something similar as a means of getting iperf3 servers to test against with my project, YABS ([yet-another-bench-script](https://github.com/masonr/yet-another-bench-script)), rather than having them hardcoded. I had a few questions to ask about your thoughts on the YABS script querying your site to select iperf3 servers for the network tests and if there was a json/csv endpoint available or in the works.

I would have reached out via email or some other means, but couldn't find any of your contact info. Would probably be best to pick this up via email (mason[@]rowe.sh) or Discord (Mason[#]9662) if you're open to this.

**Comment by R0GGER** [comment]
Interesting! I've tested a bit with json/csv, but never finished this... I send you a friend request in Discord (R0GGER[#]7459).
