### ISSUE TITLE
iperf servers for list

### ISSUE THREAD

**Issue by th3gr33n** [R0GGER/public-iperf3-servers#9]
speedtest.milkywan.fr
speedtest.studiofunk.de

both have websites with informations in regards to port locations etc pp

**Comment by R0GGER** [comment]
Nice! I'll add them as soon as I can. 
Thanks!

**Comment by R0GGER** [comment]
@th3gr33n Are you (maybe) related to studiofunk.de...? Most ports of the range 5200-5209 are closed, except for port 5200 and 5209.

http://speedtest.studiofunk.de/
_Ports zum Testen sind 5200 bis 5209_

**Comment by th3gr33n** [comment]
@R0GGER No unfortunately im not

**Comment by R0GGER** [comment]
@th3gr33n Thanks!
